Traceback (most recent call last):
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/odakyildiz/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/odakyildiz/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(12)

mu = 2
sigma = 0.5

N = 100000
x = np.zeros(N)
y = np.zeros(N)

# We use rng.normal for this
# Note that rng.normal takes the standard deviation as the second argument
# You can use Box-M\"uller transform to sample Gaussians too

for i in range(N):
    x[i] = rng.normal(mu, sigma, 1)
    y[i] = rng.normal(x[i], 1, 1)

def marginal_y(z, mu, sigma):
    return np.exp(-0.5 * (z-mu)**2/(sigma**2 + 1)) / np.sqrt(2 * np.pi * (sigma**2 + 1))

yy = np.linspace(-2, 7, 1000)
plt.hist(y, bins=100, density=True, label='y', color='black')
plt.plot(yy, marginal_y(yy, mu, sigma), label='p(y)', color=[0.8, 0, 0])
plt.legend()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      4[0m rng [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mdefault_rng([38;5;241m12[39m)

[0;31mModuleNotFoundError[0m: No module named 'numpy'

